### ISSUE TITLE
parcel-resolver-exclude-assets: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by Coder2195** [jongacnik/parcel-resolver-exclude-assets#1]
![image](https://user-images.githubusercontent.com/63069499/138460614-abff1f7a-badb-4204-bd5d-24bf92ef116e.png)

I followed all the instructions yet it isnt working

**Comment by jongacnik** [comment]
Parcel changed the `filePath` attribute to `specifier` for resolver plugins. Just published `v2.0.0` which should now work in parcel `v2.0.1`

**Comment by Coder2195** [comment]
ok thx
